# Generated by Django 3.1.2 on 2020-10-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
